name: Linux/x64 Test-Build master branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Deps
      run: sudo apt-get update -qq &&
           sudo apt-get install -y libsdl2-dev libsdl2-image-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_FORCE_SCRIPT=ON -DENABLE_EDITOR=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Tests
      timeout-minutes: 1
      run: |
        ulimit -c unlimited
        mkdir -p /home/runner/work/TheForceEngine/TheForceEngine/logs/.local/share/TheForceEngine/
        chmod -R 755 ${{github.workspace}}
        chmod +x ${{github.workspace}}/TheForceEngine/Tests/runTests.sh
        cp ${{github.workspace}}/build/theforceengine ${{github.workspace}}/TheForceEngine/
        cp ${{github.workspace}}/build/theforceengine ${{github.workspace}}/
        cp ${{github.workspace}}/build/theforceengine ${{github.workspace}}/build/TheForceEngine/              
        ${{github.workspace}}/TheForceEngine/Tests/runTests.sh ${{github.workspace}}

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: tfe_log2
        path: |
          /home/runner/work/TheForceEngine/TheForceEngine/logs/.local/share/TheForceEngine/the_force_engine_log.txt
          /home/runner/work/TheForceEngine/TheForceEngine/logs/.local/share/TheForceEngine/replay.log
        
  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Always Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tfe_log
        path: |
          /home/runner/work/TheForceEngine/TheForceEngine/logs/.local/share/TheForceEngine/the_force_engine_log.txt
          /home/runner/work/TheForceEngine/TheForceEngine/logs/.local/share/TheForceEngine/replay.log